name: Update Latest Repositories List

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update Recent Repositories List
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://github.com/LwandiNxumalo.atom"
          max_post_count: 5
          comment_tag_name: "RECENT_REPOS"
